# Travis CI (https://travis-ci.org/)
# This will only work on your repo if you have an account on travis and you
# have set it up to run continuous integration on this this repo

# Linux distribution (bionic beaver)
dist: bionic

# Language and version
language: node_js
node_js:
  - "10"

cache:
  apt: true # only works with Pro version
  directories:
  - node_modules # NPM packages for the remark markdown linter

branches:
  only:  # only run the CI for those branches 
  - master
  - dev

jobs:
  include:

    - name: "Check markdown"
      before_script:
        - npm install `cat npm-requirements.txt`
      script:
        - remark . --frail
