% (C) Copyright 2020 Remi Gau

%% A & T / Ipsi & Contra in V1 and V2
Conditions = [1 2 5 6];
RoisToSelect = {'V1', 'V2'};
Parameters = {'Cst', 'Lin'};
[model, fid] = ReturnLmmSpecAndData( ...
                                    Beta, ...
                                    RoisToSelect, ...
                                    Parameters, ...
                                    IpsiContra, ...
                                    Conditions, ...
                                    true);

% CdtNames = cellfun(@(x) x(1:5),IpsiContra, 'UniformOutput', false);
model = EstimateLmm(model);

[c, message] = ReturnContrast('F_CdtXSide', model, {'AStim'; 'TStim'});
[PVAL, F, DF1, DF2] = FTestAndPrint(model, c, message, fid);

return

%% (A - T) / Ipsi and Contra in A1 and PT
Conditions = 1:2;
[model, fid] = ReturnLmmSpecAndData( ...
                                    BetaCrossSens, ...
                                    RoisToSelect, ...
                                    Parameters, ...
                                    CrossSens, ...
                                    Conditions, ...
                                    false);
model = EstimateLmm(model);
[c, message] = ReturnContrast('F_CdtXSide', model, Conditions, CrossSens);
[PVAL, F, DF1, DF2] = TestAndPrint(model, c, message, fid);
