clear
clc
close all

StartDir = fullfile(pwd, '..','..','..','..');
cd (StartDir)

% ROIs= {...
%     'V1',...
%     'V2',...
%     'V3',...
%     'V4',...
%     'V5',...
%     'TE', ...
%     'PT',...
%     'S1_cyt',...
%         'S1_aal',...
% };

ROIs= {...
'A1',...
'V1_thres',...
'V2_thres',...
'V3_thres',...
'V4_thres',...
'V5_thres',...
'PT',...
'S1_cyt',...
'S1_aal'};

%%
ProfileFigDir = fullfile(StartDir, 'figures', 'profiles');
MVPAFigDir =  fullfile(StartDir, 'figures', 'SVM');

for iROI=1:numel(ROIs)
    
    clear FileList
    
    cd(ProfileFigDir)
    FileList(1) = dir([strrep(ROIs{iROI}, '_', '-') '-Conditions_6Layers.pdf']);
    FileList(end+1) = dir([strrep(ROIs{iROI}, '_', '-') '-Ipsilateral_6Layers.pdf']); %#ok<*SAGROW>
    FileList(end+1) = dir([strrep(ROIs{iROI}, '_', '-') '-Contralateral_6Layers.pdf']);
    FileList(end+1) = dir([strrep(ROIs{iROI}, '_', '-') '-Ipsi-Contra_6Layers.pdf']);
    FileList(end+1) = dir([strrep(ROIs{iROI}, '_', '-') '-SensModContrastsIpsi_6Layers.pdf']);
    FileList(end+1) = dir([strrep(ROIs{iROI}, '_', '-') '-SensModContrastsContra_6Layers.pdf']);
    
    Command = [];
    
    for iFile = 1:numel(FileList)
        
        disp(FileList(iFile).name)
        Command = [Command ' ' fullfile(ProfileFigDir,FileList(iFile).name)]; %#ok<*AGROW>

    end
    
    system([...
        'gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite ' ...
        '-sOutputFile=' fullfile(StartDir, 'figures', ...
        [ROIs{iROI} '_AVT_BOLD_FeatPool_Layers-6_' date '.pdf']) ' ' Command])
    
end