% (C) Copyright 2020 Remi Gau

function filename = ReturnFilename(FileType, SubjectName, HemiSphere, NbLayers, ROI, SurfParam)

    if isempty(NbLayers)
        NbLayers = 6;
    end

    switch lower(FileType)
        case 'hs_run_cdt_layer'
            filename = [ ...
                        SubjectName,  '_features', ...
                        '_hs-', HemiSphere, ...
                        '_nbLayers-', num2str(NbLayers), '.mat' ...
                       ];

        case 'hs_roi_run_cdt_layer'
            filename = [ ...
                        SubjectName, ...
                        '_hs-', HemiSphere, ...
                        '_roi-', ROI, ...
                        '_nbLayers-', num2str(NbLayers), '.mat' ...
                       ];

        case 'hs_roi_run_cdt_s-param'
            filename = [ ...
                        SubjectName, ...
                        '_hs-', HemiSphere, ...
                        '_roi-', ROI, ...
                        '_param-', lower(SurfParam), ...
                        '_nbLayers-', num2str(NbLayers), '.mat' ...
                       ];

    end
end
