clear;
clc;
close all;

StartDir = fullfile(pwd, '..', '..', '..');
cd (StartDir);

% ROIs= {...
%     'V1',...
%     'V2',...
%     'V3',...
%     'V4',...
%     'V5',...
%     'TE', ...
%     'PT';...
%     'pSTG',...
%     'S1_aal',...
%     'S1_cyt',...
%     'TE_L',...
%     'PT_L';...
%     'pSTG_L',...
%     'S1_L_cyt',...
%     'S1_L_aal',...
%     'V1_L',...
%     'V2_L',...
%     'V3_L',...
%     'V4_L',...
%     'V5_L',...
%     'TE_R',...
%     'PT_R';...
%     'pSTG_R',...
%     'S1_R_cyt',...
%     'S1_R_aal',...
%     'V1_R',...
%     'V2_R',...
%     'V3_R',...
%     'V4_R',...
%     'V5_R',...
%     };

ROIs = { ...
        'V1', ...
        'V2', ...
        'V3', ...
        'V4', ...
        'V5', ...
        'TE', ...
        'PT', ...
        'S1_cyt', ...
        'S1_aal', ...
        'TE_L', ...
        'PT_L', ...
        'S1_L_cyt', ...
        'S1_L_aal', ...
        'V1_L', ...
        'V2_L', ...
        'V3_L', ...
        'V4L', ...
        'V5L', ...
        'TE_R', ...
        'PT_R', ...
        'S1_R_cyt', ...
        'S1_R_aal', ...
        'V1_R', ...
        'V2_R', ...
        'V3_R', ...
        'V4L', ...
        'V5L' ...
       };

%%
ProfileFigDir = fullfile(StartDir, 'figures', 'profiles');
MVPAFigDir =  fullfile(StartDir, 'figures', 'SVM');

for iROI = 1:numel(ROIs)

    cd(ProfileFigDir);
    A = dir([strrep(ROIs{iROI}, '_', '-') '-Conditions_6Layers.pdf']);
    B = dir([strrep(ROIs{iROI}, '_', '-') '-SensoryModalities_6Layers.pdf']);
    C = dir([strrep(ROIs{iROI}, '_', '-') '-SideContrast_6Layers.pdf']);
    D = dir([strrep(ROIs{iROI}, '_', '-') '-SensModContrasts_6Layers.pdf']);

    %     cd(MVPAFigDir)
    %     MVPA_Fig = dir([strrep(ROIs{iROI}, '_', '-') '*_6Layers.pdf']);

    Command = [];

    for iFile = 1:numel(A)
        disp(A(iFile).name);
        disp(B(iFile).name);
        disp(C(iFile).name);
        disp(D(iFile).name);
        %         disp(MVPA_Fig(iFile).name)
        Command = [Command ' ' fullfile(ProfileFigDir, A(iFile).name)]; %#ok<*AGROW>
        Command = [Command ' ' fullfile(ProfileFigDir, B(iFile).name)]; %#ok<*AGROW>
        Command = [Command ' ' fullfile(ProfileFigDir, C(iFile).name)]; %#ok<*AGROW>
        Command = [Command ' ' fullfile(ProfileFigDir, D(iFile).name)]; %#ok<*AGROW>
        %         Command = [Command ' ' fullfile(MVPAFigDir,MVPA_Fig(iFile).name)];
    end

    system([ ...
            'gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite ' ...
            '-sOutputFile=' fullfile(StartDir, 'figures', ...
                                     [ROIs{iROI} '_BOLD_Layers-6_' date '.pdf']) ' ' Command]);

end
