% (C) Copyright 2020 Remi Gau

function  [CondNames, IpsiContra, CrossSide, CrossSens] = GetConditionList()
    %
    % Returns the names of the conditions used in analysis
    %
    % USAGE::
    %
    %    [CondNames, CondNamesIpsiContra] = GetConditionList()
    %

    CondNames = { ...
                 'AStimL', 'AStimR', ...
                 'VStimL', 'VStimR', ...
                 'TStimL', 'TStimR', ...
                 'ATargL', 'ATargR', ...
                 'VTargL', 'VTargR', ...
                 'TTargL', 'TTargR' ...
                };

    IpsiContra = { ...
                  'AStimIpsi', 'AStimContra', ...
                  'VStimIpsi', 'VStimContra', ...
                  'TStimIpsi', 'TStimContra', ...
                  'ATargIpsi', 'ATargContra', ...
                  'VTargIpsi', 'VTargContra', ...
                  'TTargIpsi', 'TTargContra' ...
                 };

    CrossSide = { ...
                 '[Contra-Ipsi]_AStim', ...
                 '[Contra-Ipsi]_VStim', ...
                 '[Contra-Ipsi]_TStim', ...
                 '[Contra-Ipsi]_ATarg', ...
                 '[Contra-Ipsi]_VTarg', ...
                 '[Contra-Ipsi]_TTarg' ...
                };

    CrossSens = { ...
                 '[A-T]_{stim ipsi}', '[A-T]_{stim contra}'; ...
                 '[V-T]_{stim ipsi}', '[V-T]_{stim contra}'; ...
                 '[A-T]_{target ipsi}', '[A-T]_{target contra}'; ...
                 '[V-T]_{target ipsi}', '[V-T]_{target contra}'};

end
