name: "Pull Request Docs Check"

on:
  push:
    branches:
      - master
      - remi-dev
  pull_request:
    branches: '*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"